[package]
name = "example"
version = "0.0.0"
authors = ["Paul Grandperrin <paul.grandperrin@gmail.com>"]

[dependencies]
honggfuzz = {path = ".."}
# arbitrary = "0.1"
libc = "*"
positioned-io = "*"
tempfile = "*"
